### ISSUE TITLE
Presence of FWD-Pseudo-record crashes the webhook

### ISSUE THREAD

**Issue by mstarostik** [mirceanton/external-dns-provider-mikrotik#133]
Affected release: v1.2.1

If there is a FWD record configured on the router (Mikrotik's pseudo-record type for configuring a domain specific forwarder) the webhook crashes fetching entries:

```
webhook {"level":"info","msg":"fetching all DNS records","time":"2024-12-10T00:40:39Z"}                                                                                         
webhook 2024/12/10 00:40:39 http: panic serving 127.0.0.1:43274: runtime error: invalid memory address or nil pointer dereference                                               
webhook goroutine 52 [running]:                                                                                                                                                 
webhook net/http.(*conn).serve.func1()                                                                                                                                          
webhook     /opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:1947 +0xbe                                                                                                
webhook panic({0xc23840?, 0x14e5280?})                                                                                                                                          
webhook     /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/panic.go:785 +0x132                                                                                                  
webhook github.com/mirceanton/external-dns-provider-mikrotik/internal/mikrotik.(*MikrotikProvider).Records(0xc00017e0f0, {0xc0001b9968?, 0xc0001b9848?})                        
webhook     /home/runner/work/external-dns-provider-mikrotik/external-dns-provider-mikrotik/internal/mikrotik/provider.go:57 +0x195                                             
webhook github.com/mirceanton/external-dns-provider-mikrotik/pkg/webhook.(*Webhook).Records(0xc00019c140, {0xf38a40, 0xc0001dc000}, 0xc000234140)                               
webhook     /home/runner/work/external-dns-provider-mikrotik/external-dns-provider-mikrotik/pkg/webhook/webhook.go:103 +0x4ba                                                   
webhook net/http.HandlerFunc.ServeHTTP(0xc0001e0000?, {0xf38a40?, 0xc0001dc000?}, 0xc0001be01c?)                                                                                
webhook     /opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:2220 +0x29                                                                                                
webhook github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000180120, {0xf38a40, 0xc0001dc000}, 0xc000234140)                                                                         
webhook     /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459 +0x2e2                                                                                           
webhook net/http.HandlerFunc.ServeHTTP(0xf3a618?, {0xf38a40?, 0xc0001dc000?}, 0x14e50d0?)                                                                                       
webhook     /opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:2220 +0x29                                                                                                
webhook github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000180120, {0xf38a40, 0xc0001dc000}, 0xc000234000)                                                                         
webhook     /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90 +0x2ee                                                                                            
webhook net/http.serverHandler.ServeHTTP({0xc00059fd70?}, {0xf38a40?, 0xc0001dc000?}, 0x6?)                                                                                     
webhook     /opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:3210 +0x8e                                                                                                
webhook net/http.(*conn).serve(0xc000002000, {0xf3a5e0, 0xc00059fc80})                                                                                                          
webhook     /opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:2092 +0x5d0                                                                                               
webhook created by net/http.(*Server).Serve in goroutine 6                                                                                                                      
webhook     /opt/hostedtoolcache/go/1.23.4/x64/src/net/http/server.go:3360 +0x485                                                                                               
```

This is the only record on the router:
```
[admin@Router] > /ip/dns/static/ print detail
Flags: D - dynamic; X - disabled 
 0    name="wave" type=FWD forward-to=10.26.0.1 ttl=1d match-subdomain=yes 
```

When I remove it, external-dns's records are created as they should.

**Comment by mircea-pavel-anton** [comment]
Hello, @mstarostik !

Thanks for reporting this bug. I'll look into it as soon as possible.

Can you also tell me the version of routerOS are you running?

**Comment by mstarostik** [comment]
Thanks for looking into it.
Got this on a hEX PoE (RB960PGS) running RouterOS 7.17beta5

**Comment by mircea-pavel-anton** [comment]
I haven't tested this on beta versions of rOS, but I seem to recall having this working on my 7.16 install on my RB5009.

I'll see if I can update and reproduce. I'll post an update here

**Comment by mircea-pavel-anton** [comment]
Managed to reproduce. It seems the webhook is trying to convert the Mikrotik FWD record to a format eDNS would understand and is failing somewhere. I'm investigating further

**Comment by mircea-pavel-anton** [comment]
@mstarostik I think I managed to fix it and `v1.2.2` should be out in a few minutes.

Let me know if the new patch fixed it!

**Comment by mstarostik** [comment]
v1.2.2 is working just fine. Thank you for the quick fix :+1:

**Comment by mircea-pavel-anton** [comment]
I'm glad to hear that! Thank you for the detailed bug report!
